= Set up log4j2
:toc:

Just arranges dependencies to set up log4j2. Arranges logging from jul and slf4j (1 &amp; 2) to log4j2.

== Usage

Add the dependency to your project:
[source,xml]
----
<dependency>
  <groupId>nl.mmprogrami</groupId>
  <artifactId>setup-log4j2</artifactId>
  <version>1.1</version>
</dependency>
----

This basically boils down to only two things:

. It'll transitively pull in necessary dependencies
. will route JUL and SLF4J (1 &amp; 2) to log4j2, so you can use those APIs and have the output end up in log4j2.

The only thing left to do is add a 'log4j2.xml' configuration file to your project, and you're good to go.

== As a test dependency

This is possible too:

[source,xml]
----
<dependency>
  <groupId>nl.mmprogrami</groupId>
  <artifactId>setup-log4j2</artifactId>
  <version>1.1</version>
  <classifier>test</classifier>
  <scope>test</scope>
</dependency>
----
This will accomplish the same things, but this jar also includes a default `log4j2-test.xml` configuration file, which will then be used when running tests. This is useful if you want to use logging in your test with minimal hassle in setting it up. You don't even have to provide log4j2 configuration then. It will log INFO and above to the console.

=== Override the root level

This can be done with the system property log4j2.root.level

[source, bash]
----
mvn -Dlog4j2.root.level=debug test
----

Or like so:

[source, xml]
----
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>3.5.5</version>
   <configuration>
     <systemPropertyVariables>
        <log4j2.root.level>debug</log4j2.root.level>
        <log4j2.pattern>%d{ISO8601}&#x09;%highlight{%5.5p}&#x09;%c{1}&#x09;%m%n</log4j2.pattern>
     </systemPropertyVariables>
....
----
